// Mocks generated by Mockito 5.4.4 from annotations
// in smart_route_app/test/features/map/domain/usecases/get_incidents_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:smart_route_app/core/errors/failures.dart' as _i5;
import 'package:smart_route_app/features/map/domain/entities/incident.dart'
    as _i6;
import 'package:smart_route_app/features/map/domain/repositories/incident_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IncidentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIncidentRepository extends _i1.Mock
    implements _i2.IncidentRepository {
  MockIncidentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Incident>>>
      getIncidentsFormArcGis() => (super.noSuchMethod(
            Invocation.method(
              #getIncidentsFormArcGis,
              [],
            ),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Incident>>>.value(
                    _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Incident>>>(
              this,
              Invocation.method(
                #getIncidentsFormArcGis,
                [],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Incident>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> addIncident(
          _i6.Incident? incident) =>
      (super.noSuchMethod(
        Invocation.method(
          #addIncident,
          [incident],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #addIncident,
            [incident],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteIncident({
    required String? incidentId,
    required String? userUid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteIncident,
          [],
          {
            #incidentId: incidentId,
            #userUid: userUid,
          },
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #deleteIncident,
            [],
            {
              #incidentId: incidentId,
              #userUid: userUid,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.Incident>>>
      getIncidentsFromSupabase({required String? userUid}) =>
          (super.noSuchMethod(
            Invocation.method(
              #getIncidentsFromSupabase,
              [],
              {#userUid: userUid},
            ),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i6.Incident>>>.value(
                    _i7.dummyValue<_i4.Either<_i5.Failure, List<_i6.Incident>>>(
              this,
              Invocation.method(
                #getIncidentsFromSupabase,
                [],
                {#userUid: userUid},
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.Incident>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateIncident(
    _i6.Incident? incident, {
    required String? userUid,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateIncident,
          [incident],
          {#userUid: userUid},
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #updateIncident,
            [incident],
            {#userUid: userUid},
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<int> getCachedIncidentCount() => (super.noSuchMethod(
        Invocation.method(
          #getCachedIncidentCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> clearIncidentCache() => (super.noSuchMethod(
        Invocation.method(
          #clearIncidentCache,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
