// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzudSybFI5pDT1wZ55HFluvcYk29TUFbA',
    appId: '1:1094897979700:web:91ffa7becc27fdf26fd561',
    messagingSenderId: '1094897979700',
    projectId: 'smart-route-find-application',
    authDomain: 'smart-route-find-application.firebaseapp.com',
    storageBucket: 'smart-route-find-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ9KpOdjXla4JkvD39rIUdR9jPgAbGNbM',
    appId: '1:1094897979700:android:890b91e0127c158d6fd561',
    messagingSenderId: '1094897979700',
    projectId: 'smart-route-find-application',
    storageBucket: 'smart-route-find-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFjodm7ikkeoh96xy0EjbVEgV4Ogb5jpc',
    appId: '1:1094897979700:ios:df7b1255b61d95446fd561',
    messagingSenderId: '1094897979700',
    projectId: 'smart-route-find-application',
    storageBucket: 'smart-route-find-application.firebasestorage.app',
    iosBundleId: 'com.thanh.smartroutefindapplication',
  );
}
