// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9Kq78XCGw6QvM2g7FXfTfjkCDhlHVbE',
    appId: '1:1094897979700:web:bfb207b75b3f161a6fd561',
    messagingSenderId: '1094897979700',
    projectId: 'smart-route-find-application',
    authDomain: 'smart-route-find-application.firebaseapp.com',
    storageBucket: 'smart-route-find-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ9KpOdjXla4JkvD39rIUdR9jPgAbGNbM',
    appId: '1:1094897979700:android:f8cbe6e7ddd58a9d6fd561',
    messagingSenderId: '1094897979700',
    projectId: 'smart-route-find-application',
    storageBucket: 'smart-route-find-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFjodm7ikkeoh96xy0EjbVEgV4Ogb5jpc',
    appId: '1:1094897979700:ios:b3162307b7e007b76fd561',
    messagingSenderId: '1094897979700',
    projectId: 'smart-route-find-application',
    storageBucket: 'smart-route-find-application.firebasestorage.app',
    iosBundleId: 'com.example.smartRouteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFjodm7ikkeoh96xy0EjbVEgV4Ogb5jpc',
    appId: '1:1094897979700:ios:b3162307b7e007b76fd561',
    messagingSenderId: '1094897979700',
    projectId: 'smart-route-find-application',
    storageBucket: 'smart-route-find-application.firebasestorage.app',
    iosBundleId: 'com.example.smartRouteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ9Kq78XCGw6QvM2g7FXfTfjkCDhlHVbE',
    appId: '1:1094897979700:web:ca1f37c8b61e49326fd561',
    messagingSenderId: '1094897979700',
    projectId: 'smart-route-find-application',
    authDomain: 'smart-route-find-application.firebaseapp.com',
    storageBucket: 'smart-route-find-application.firebasestorage.app',
  );

}